### ISSUE TITLE
mini-coi.js not happy.... at all

### ISSUE THREAD

**Issue by fpliger** [pyscript/docs#42]
JS Console shows `mini-coi.js` complaining about scope within `ServiceWorker` registration.

```
docs.pyscript.net/:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://docs.pyscript.net/2023.11.1.RC3/beginning-pyscript/') with script ('https://docs.pyscript.net/2023.11.1.RC3/javascripts/mini-coi.js'): The path of the provided scope ('/2023.11.1.RC3/beginning-pyscript/') is not under the max scope allowed ('/2023.11.1.RC3/javascripts/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.
```

 I also guess (total guess actually but I think @JeffersGlass looked into it) that it may be interfering with our ability to use `pyscript-mkdocs` to actually make the examples interactive

**Comment by JeffersGlass** [comment]
So Service Workers [can't have a scope broader than their own location](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register) - since we're serving `mini-coi.js` out of the `/javascripts` folder, it can't service any pages not under the `/javascript` path - which is to say, none of them. 

The solution* is to move mini-coi.js to the root of the docs. I'll open a PR.

*We could also write a [mkdocs hook](https://www.mkdocs.org/user-guide/configuration/#hooks) to change where that script is loaded, but that seems error prone. Maybe for the future.

**Comment by JeffersGlass** [comment]
Oh weird.

With `mini-coi.js` under the JavaScripts folder, I see that error in the console but, at least serving locally with a (non COI) dev server, the embedded examples work fine.

When I move `mini-coi.js` to root and adjust `mkdocs.yml` appropriately, the console errors go away... but the embedded demos stop working...

**Comment by WebReflection** [comment]
mini-coi is an escape hatch for users hosting in GitHub pages or places where they cannot control server headers … why can’t we have headers properly setup? 🤔 

that being said, it’s just a ServiceWorker and it cannot escape ServiceWorker restrictions but because more than a SW can be registered we could as well do both. It doesn’t cache network requests so it’s not a sticky SW hard to deal with.

**Comment by fpliger** [comment]
> mini-coi is an escape hatch for users hosting in GitHub pages or places where they cannot control server headers … why can’t we have headers properly setup? 🤔

Nice.. I'm glad you are asking/clarifying since that was exactly my first question 😄  . That's what I told @JeffersGlass  on Friday "I understand `mini-coi` in `pyscript-mkdocs` for same reason you mentioned (that plugin can't always control server headers) but was wondering why we added to our own docs. :D  

Maybe @ntoll  has more insights

**Comment by JeffersGlass** [comment]
> why can’t we have headers properly setup? 🤔

Don't see any reason why we couldn't, it's a policy that would have to be setup on the S3 bucket that hosts the docs. That would be an Anaconda infrastructure thing, but would be great if it works.

**Comment by ntoll** [comment]
(P.S. I guess it's good that *we* feel this pain - so we're more informed for our users who may encounter similar situations)
